# Generated by Django 5.2.8 on 2026-07-06 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateField(blank=True, help_text='La date à laquelle le paiement a été effectué.', null=True)),
                ('date_echeance', models.DateField(help_text='La date à laquelle le paiement est attendu.')),
                ('type_paiement', models.CharField(choices=[('LOYER', 'Loyer'), ('CAUTION', 'Caution'), ('FRAIS_AGENCE', "Frais d'agence"), ('AUTRE', 'Autre')], default='LOYER', max_length=20)),
                ('statut', models.CharField(choices=[('PAYE', 'Payé'), ('EN_ATTENTE', 'En attente'), ('EN_RETARD', 'En retard'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='app_base.personnel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.client')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='app_base.contrat')),
            ],
        ),
    ]
