# Generated by Django 5.2.8 on 2026-03-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_paiements', '0001_initial'),
    ]

    operations = [
    ]
