# Generated by Django 5.2.8 on 2026-03-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_base', '0001_initial'),
        ('app_paiements', '0002_auto_20260310_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impayes',
            fields=[
                ('id_impaye', models.IntegerField(primary_key=True, serialize=False)),
                ('impaye', models.IntegerField()),
                ('situation', models.CharField(max_length=50)),
                ('date_sortie', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locataires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paie', models.IntegerField(primary_key=True, serialize=False)),
                ('Montant', models.IntegerField()),
                ('date_paie', models.DateField()),
                ('date_normal', models.DateField()),
                ('type_paie', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locataires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.locataire')),
            ],
        ),
    ]
