# Generated by Django 5.2.8 on 2026-02-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id_caisse', models.IntegerField(primary_key=True, serialize=False)),
                ('status_caisse', models.CharField(max_length=50)),
                ('cout', models.IntegerField()),
                ('paiement', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'caisse',
                'managed': False,
            },
        ),
    ]
