# Generated by Django 5.2.8 on 2026-03-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_paiements', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id_caisse', models.IntegerField(primary_key=True, serialize=False)),
                ('type_caisse', models.CharField(default='Entree', max_length=50)),
                ('status_caisse', models.CharField(max_length=50)),
                ('cout', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_paiements.paiement')),
            ],
        ),
    ]
