# Generated by Django 5.2.8 on 2026-07-06 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_paiements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_caisse', models.CharField(default='Entree', max_length=50)),
                ('status_caisse', models.CharField(max_length=50)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('details', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_paiements.paiement')),
            ],
        ),
    ]
