# Generated by Django 5.2.8 on 2026-02-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id_agence', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('numero_impot', models.CharField(max_length=50)),
                ('numero_fisc', models.CharField(max_length=50)),
                ('effectif', models.IntegerField(default=0)),
                ('revenu', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id_appartement', models.IntegerField(primary_key=True, serialize=False)),
                ('identifiant', models.CharField(max_length=50)),
                ('prix', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appartement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garantie',
            fields=[
                ('id_garantie', models.IntegerField(primary_key=True, serialize=False)),
                ('montant', models.IntegerField()),
                ('planification', models.CharField(max_length=50)),
                ('date_appartition', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'garantie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id_locataire', models.IntegerField(primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('contrat', models.CharField(max_length=50)),
                ('loye', models.IntegerField(default=0)),
                ('regularite', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locataire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id_logement', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'logement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id_personnel', models.IntegerField(primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('ND', 'Non défini')], max_length=2)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id_proprietaire', models.IntegerField(primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=50)),
                ('bienconfie', models.IntegerField(blank=True, null=True)),
                ('bienlocatif', models.IntegerField(blank=True, null=True)),
                ('catalogue', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proprietaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id_propriete', models.IntegerField(primary_key=True, serialize=False)),
                ('type_propiete', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('Agent', models.CharField(max_length=50)),
                ('gestion', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'propriete',
                'managed': False,
            },
        ),
    ]
