# Generated by Django 5.2.8 on 2026-06-28 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='app_base.client'),
        ),
        migrations.AddField(
            model_name='garantie',
            name='contrat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garantie', to='app_base.contrat'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='logement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='app_base.logement'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='logement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='app_base.logement'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='app_base.agence'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_geres', to='app_base.personnel'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to='app_base.agence'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propriete',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to='app_base.agence'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietes_gerees', to='app_base.personnel'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to='app_base.proprietaire'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='app_base.propriete'),
        ),
        migrations.AddField(
            model_name='logement',
            name='propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements', to='app_base.propriete'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='propriete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='app_base.propriete'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='type_propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_base.typepropriete'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('logement__isnull', True), ('propriete__isnull', False)), models.Q(('logement__isnull', False), ('propriete__isnull', True)), _connector='OR'), name='un_seul_bien_par_contrat'),
        ),
    ]
